### PR TITLE
Cleanup of the template.

### PR DESCRIPTION
**Pull request by jdewinkel**
- Added auto generation of PDF for logo
- Removed student number
- Added optional line about paper
- Adjusted makefile to be more flexible
- Added gitignore for all outputs

### CODE REVIEW

**Comment by przemyslaw-pawelczak** [comment]
Thank you @jdewinkel for the changes. All looks good. I would request small change to these revisions though: please remove (_not_ comment) references to student numbers - I'm afraid students will attempt to un-comment this line anyway. Thanks in advance for correcting this.

**Comment by jdewinkel** [comment]
Done. :+1:

**Comment by przemyslaw-pawelczak** [comment]
Great! Thank you @jdewinkel

**Review by przemyslaw-pawelczak — COMMENTED** [review]
All looks great! Thank you @jdewinkel

**Pull request merged**
